# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'demo.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QHBoxLayout, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1280, 720)
        self.pushButton_load_parsing = QPushButton(Form)
        self.pushButton_load_parsing.setObjectName(u"pushButton_load_parsing")
        self.pushButton_load_parsing.setGeometry(QRect(320, 20, 125, 30))
        self.pushButton_load_parsing.setMinimumSize(QSize(125, 25))
        self.pushButton_load_pose = QPushButton(Form)
        self.pushButton_load_pose.setObjectName(u"pushButton_load_pose")
        self.pushButton_load_pose.setGeometry(QRect(320, 60, 125, 30))
        self.pushButton_load_pose.setMinimumSize(QSize(125, 25))
        self.pushButton_save_output = QPushButton(Form)
        self.pushButton_save_output.setObjectName(u"pushButton_save_output")
        self.pushButton_save_output.setGeometry(QRect(465, 60, 125, 30))
        self.pushButton_save_output.setMinimumSize(QSize(125, 25))
        self.pushButton_clear = QPushButton(Form)
        self.pushButton_clear.setObjectName(u"pushButton_clear")
        self.pushButton_clear.setGeometry(QRect(320, 100, 125, 30))
        self.pushButton_clear.setMinimumSize(QSize(125, 25))
        self.pushButton_save_parsing = QPushButton(Form)
        self.pushButton_save_parsing.setObjectName(u"pushButton_save_parsing")
        self.pushButton_save_parsing.setGeometry(QRect(465, 100, 125, 30))
        self.pushButton_save_parsing.setMinimumSize(QSize(125, 25))
        self.pushButton_generate = QPushButton(Form)
        self.pushButton_generate.setObjectName(u"pushButton_generate")
        self.pushButton_generate.setGeometry(QRect(465, 22, 125, 30))
        self.pushButton_generate.setMinimumSize(QSize(125, 25))
        self.graphicsView_parsing = QGraphicsView(Form)
        self.graphicsView_parsing.setObjectName(u"graphicsView_parsing")
        self.graphicsView_parsing.setGeometry(QRect(100, 160, 256, 512))
        self.graphicsView_parsing.setMinimumSize(QSize(256, 512))
        self.graphicsView_pose = QGraphicsView(Form)
        self.graphicsView_pose.setObjectName(u"graphicsView_pose")
        self.graphicsView_pose.setGeometry(QRect(376, 160, 256, 512))
        self.graphicsView_pose.setMinimumSize(QSize(256, 512))
        self.graphicsView_output = QGraphicsView(Form)
        self.graphicsView_output.setObjectName(u"graphicsView_output")
        self.graphicsView_output.setGeometry(QRect(652, 160, 256, 512))
        self.graphicsView_output.setMinimumSize(QSize(256, 512))
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(610, 50, 300, 80))
        self.lineEdit.setMinimumSize(QSize(300, 75))
        self.label_text_discription = QLabel(Form)
        self.label_text_discription.setObjectName(u"label_text_discription")
        self.label_text_discription.setGeometry(QRect(610, 20, 300, 30))
        self.label_text_discription.setMinimumSize(QSize(300, 25))
        self.label_text_discription.setMaximumSize(QSize(16777215, 16777215))
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(950, 20, 262, 370))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.pushButton_top = QPushButton(self.layoutWidget)
        self.pushButton_top.setObjectName(u"pushButton_top")
        self.pushButton_top.setMinimumSize(QSize(125, 25))
        font = QFont()
        font.setFamilies([u"Meiryo UI"])
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_top.setFont(font)
        self.pushButton_top.setAutoFillBackground(False)
        icon = QIcon()
        icon.addFile(u"color_blocks/class_top.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_top.setIcon(icon)
        self.pushButton_top.setAutoDefault(False)
        self.pushButton_top.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_top)

        self.pushButton_skin = QPushButton(self.layoutWidget)
        self.pushButton_skin.setObjectName(u"pushButton_skin")
        self.pushButton_skin.setMinimumSize(QSize(125, 25))
        font1 = QFont()
        font1.setFamilies([u"Microsoft YaHei UI"])
        font1.setPointSize(10)
        font1.setBold(False)
        self.pushButton_skin.setFont(font1)
        icon1 = QIcon()
        icon1.addFile(u"color_blocks/class_skin.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_skin.setIcon(icon1)
        self.pushButton_skin.setAutoDefault(False)
        self.pushButton_skin.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_skin)

        self.pushButton_outer = QPushButton(self.layoutWidget)
        self.pushButton_outer.setObjectName(u"pushButton_outer")
        self.pushButton_outer.setMinimumSize(QSize(125, 25))
        self.pushButton_outer.setFont(font1)
        icon2 = QIcon()
        icon2.addFile(u"color_blocks/class_outer.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_outer.setIcon(icon2)
        self.pushButton_outer.setAutoDefault(False)
        self.pushButton_outer.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_outer)

        self.pushButton_face = QPushButton(self.layoutWidget)
        self.pushButton_face.setObjectName(u"pushButton_face")
        self.pushButton_face.setMinimumSize(QSize(125, 25))
        self.pushButton_face.setFont(font1)
        icon3 = QIcon()
        icon3.addFile(u"color_blocks/class_face.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_face.setIcon(icon3)
        self.pushButton_face.setAutoDefault(False)
        self.pushButton_face.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_face)

        self.pushButton_skirt = QPushButton(self.layoutWidget)
        self.pushButton_skirt.setObjectName(u"pushButton_skirt")
        self.pushButton_skirt.setMinimumSize(QSize(125, 25))
        self.pushButton_skirt.setFont(font1)
        icon4 = QIcon()
        icon4.addFile(u"color_blocks/class_skirt.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_skirt.setIcon(icon4)
        self.pushButton_skirt.setAutoDefault(False)
        self.pushButton_skirt.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_skirt)

        self.pushButton_hair = QPushButton(self.layoutWidget)
        self.pushButton_hair.setObjectName(u"pushButton_hair")
        self.pushButton_hair.setMinimumSize(QSize(125, 25))
        self.pushButton_hair.setFont(font1)
        icon5 = QIcon()
        icon5.addFile(u"color_blocks/class_hair.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_hair.setIcon(icon5)
        self.pushButton_hair.setAutoDefault(False)
        self.pushButton_hair.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_hair)

        self.pushButton_dress = QPushButton(self.layoutWidget)
        self.pushButton_dress.setObjectName(u"pushButton_dress")
        self.pushButton_dress.setMinimumSize(QSize(125, 25))
        self.pushButton_dress.setFont(font1)
        icon6 = QIcon()
        icon6.addFile(u"color_blocks/class_dress.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_dress.setIcon(icon6)
        self.pushButton_dress.setAutoDefault(False)
        self.pushButton_dress.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_dress)

        self.pushButton_headwear = QPushButton(self.layoutWidget)
        self.pushButton_headwear.setObjectName(u"pushButton_headwear")
        self.pushButton_headwear.setMinimumSize(QSize(125, 25))
        self.pushButton_headwear.setFont(font1)
        icon7 = QIcon()
        icon7.addFile(u"color_blocks/class_headwear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_headwear.setIcon(icon7)
        self.pushButton_headwear.setAutoDefault(False)
        self.pushButton_headwear.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_headwear)

        self.pushButton_pants = QPushButton(self.layoutWidget)
        self.pushButton_pants.setObjectName(u"pushButton_pants")
        self.pushButton_pants.setMinimumSize(QSize(125, 25))
        self.pushButton_pants.setFont(font1)
        icon8 = QIcon()
        icon8.addFile(u"color_blocks/class_pants.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_pants.setIcon(icon8)
        self.pushButton_pants.setAutoDefault(False)
        self.pushButton_pants.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_pants)

        self.pushButton_eyeglass = QPushButton(self.layoutWidget)
        self.pushButton_eyeglass.setObjectName(u"pushButton_eyeglass")
        self.pushButton_eyeglass.setMinimumSize(QSize(125, 25))
        self.pushButton_eyeglass.setFont(font1)
        icon9 = QIcon()
        icon9.addFile(u"color_blocks/class_eyeglass.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_eyeglass.setIcon(icon9)
        self.pushButton_eyeglass.setAutoDefault(False)
        self.pushButton_eyeglass.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_eyeglass)

        self.pushButton_rompers = QPushButton(self.layoutWidget)
        self.pushButton_rompers.setObjectName(u"pushButton_rompers")
        self.pushButton_rompers.setMinimumSize(QSize(125, 25))
        self.pushButton_rompers.setFont(font1)
        icon10 = QIcon()
        icon10.addFile(u"color_blocks/class_rompers.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_rompers.setIcon(icon10)
        self.pushButton_rompers.setAutoDefault(False)
        self.pushButton_rompers.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_rompers)

        self.pushButton_footwear = QPushButton(self.layoutWidget)
        self.pushButton_footwear.setObjectName(u"pushButton_footwear")
        self.pushButton_footwear.setMinimumSize(QSize(125, 25))
        self.pushButton_footwear.setFont(font1)
        icon11 = QIcon()
        icon11.addFile(u"color_blocks/class_footwear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_footwear.setIcon(icon11)
        self.pushButton_footwear.setAutoDefault(False)
        self.pushButton_footwear.setFlat(False)

        self.verticalLayout_4.addWidget(self.pushButton_footwear)


        self.horizontalLayout_3.addLayout(self.verticalLayout_4)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.pushButton_leggings = QPushButton(self.layoutWidget)
        self.pushButton_leggings.setObjectName(u"pushButton_leggings")
        self.pushButton_leggings.setMinimumSize(QSize(125, 25))
        self.pushButton_leggings.setFont(font1)
        icon12 = QIcon()
        icon12.addFile(u"color_blocks/class_leggings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_leggings.setIcon(icon12)
        self.pushButton_leggings.setAutoDefault(False)
        self.pushButton_leggings.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_leggings)

        self.pushButton_ring = QPushButton(self.layoutWidget)
        self.pushButton_ring.setObjectName(u"pushButton_ring")
        self.pushButton_ring.setMinimumSize(QSize(125, 25))
        self.pushButton_ring.setFont(font1)
        icon13 = QIcon()
        icon13.addFile(u"color_blocks/class_ring.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_ring.setIcon(icon13)
        self.pushButton_ring.setAutoDefault(False)
        self.pushButton_ring.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_ring)

        self.pushButton_belt = QPushButton(self.layoutWidget)
        self.pushButton_belt.setObjectName(u"pushButton_belt")
        self.pushButton_belt.setMinimumSize(QSize(125, 25))
        self.pushButton_belt.setFont(font1)
        icon14 = QIcon()
        icon14.addFile(u"color_blocks/class_belt.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_belt.setIcon(icon14)
        self.pushButton_belt.setAutoDefault(False)
        self.pushButton_belt.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_belt)

        self.pushButton_neckwear = QPushButton(self.layoutWidget)
        self.pushButton_neckwear.setObjectName(u"pushButton_neckwear")
        self.pushButton_neckwear.setMinimumSize(QSize(125, 25))
        self.pushButton_neckwear.setFont(font1)
        icon15 = QIcon()
        icon15.addFile(u"color_blocks/class_neckwear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_neckwear.setIcon(icon15)
        self.pushButton_neckwear.setAutoDefault(False)
        self.pushButton_neckwear.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_neckwear)

        self.pushButton_wristwear = QPushButton(self.layoutWidget)
        self.pushButton_wristwear.setObjectName(u"pushButton_wristwear")
        self.pushButton_wristwear.setMinimumSize(QSize(125, 25))
        self.pushButton_wristwear.setFont(font1)
        icon16 = QIcon()
        icon16.addFile(u"color_blocks/class_wrist.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_wristwear.setIcon(icon16)
        self.pushButton_wristwear.setAutoDefault(False)
        self.pushButton_wristwear.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_wristwear)

        self.pushButton_socks = QPushButton(self.layoutWidget)
        self.pushButton_socks.setObjectName(u"pushButton_socks")
        self.pushButton_socks.setMinimumSize(QSize(125, 25))
        self.pushButton_socks.setFont(font1)
        icon17 = QIcon()
        icon17.addFile(u"color_blocks/class_socks.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_socks.setIcon(icon17)
        self.pushButton_socks.setAutoDefault(False)
        self.pushButton_socks.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_socks)

        self.pushButton_tie = QPushButton(self.layoutWidget)
        self.pushButton_tie.setObjectName(u"pushButton_tie")
        self.pushButton_tie.setMinimumSize(QSize(125, 25))
        self.pushButton_tie.setFont(font1)
        icon18 = QIcon()
        icon18.addFile(u"color_blocks/class_tie.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_tie.setIcon(icon18)
        self.pushButton_tie.setAutoDefault(False)
        self.pushButton_tie.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_tie)

        self.pushButton_necklace = QPushButton(self.layoutWidget)
        self.pushButton_necklace.setObjectName(u"pushButton_necklace")
        self.pushButton_necklace.setMinimumSize(QSize(125, 25))
        self.pushButton_necklace.setFont(font1)
        icon19 = QIcon()
        icon19.addFile(u"color_blocks/class_necklace.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_necklace.setIcon(icon19)
        self.pushButton_necklace.setAutoDefault(False)
        self.pushButton_necklace.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_necklace)

        self.pushButton_earrings = QPushButton(self.layoutWidget)
        self.pushButton_earrings.setObjectName(u"pushButton_earrings")
        self.pushButton_earrings.setMinimumSize(QSize(125, 25))
        self.pushButton_earrings.setFont(font1)
        icon20 = QIcon()
        icon20.addFile(u"color_blocks/class_earstuds.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_earrings.setIcon(icon20)
        self.pushButton_earrings.setAutoDefault(False)
        self.pushButton_earrings.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_earrings)

        self.pushButton_bag = QPushButton(self.layoutWidget)
        self.pushButton_bag.setObjectName(u"pushButton_bag")
        self.pushButton_bag.setMinimumSize(QSize(125, 25))
        self.pushButton_bag.setFont(font1)
        icon21 = QIcon()
        icon21.addFile(u"color_blocks/class_bag.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_bag.setIcon(icon21)
        self.pushButton_bag.setAutoDefault(False)
        self.pushButton_bag.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_bag)

        self.pushButton_gloves = QPushButton(self.layoutWidget)
        self.pushButton_gloves.setObjectName(u"pushButton_gloves")
        self.pushButton_gloves.setMinimumSize(QSize(125, 25))
        self.pushButton_gloves.setFont(font1)
        icon22 = QIcon()
        icon22.addFile(u"color_blocks/class_glove.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_gloves.setIcon(icon22)
        self.pushButton_gloves.setAutoDefault(False)
        self.pushButton_gloves.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_gloves)

        self.pushButton_background = QPushButton(self.layoutWidget)
        self.pushButton_background.setObjectName(u"pushButton_background")
        self.pushButton_background.setMinimumSize(QSize(125, 25))
        self.pushButton_background.setFont(font1)
        icon23 = QIcon()
        icon23.addFile(u"color_blocks/class_bg.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_background.setIcon(icon23)
        self.pushButton_background.setAutoDefault(False)
        self.pushButton_background.setFlat(False)

        self.verticalLayout_5.addWidget(self.pushButton_background)


        self.horizontalLayout_3.addLayout(self.verticalLayout_5)

        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 20, 100, 100))
        self.label.setPixmap(QPixmap(u"logo.png"))
        self.label.setScaledContents(True)

        self.retranslateUi(Form)

        self.pushButton_top.setDefault(False)
        self.pushButton_skin.setDefault(False)
        self.pushButton_outer.setDefault(False)
        self.pushButton_face.setDefault(False)
        self.pushButton_skirt.setDefault(False)
        self.pushButton_hair.setDefault(False)
        self.pushButton_dress.setDefault(False)
        self.pushButton_headwear.setDefault(False)
        self.pushButton_pants.setDefault(False)
        self.pushButton_eyeglass.setDefault(False)
        self.pushButton_rompers.setDefault(False)
        self.pushButton_footwear.setDefault(False)
        self.pushButton_leggings.setDefault(False)
        self.pushButton_ring.setDefault(False)
        self.pushButton_belt.setDefault(False)
        self.pushButton_neckwear.setDefault(False)
        self.pushButton_wristwear.setDefault(False)
        self.pushButton_socks.setDefault(False)
        self.pushButton_tie.setDefault(False)
        self.pushButton_necklace.setDefault(False)
        self.pushButton_earrings.setDefault(False)
        self.pushButton_bag.setDefault(False)
        self.pushButton_gloves.setDefault(False)
        self.pushButton_background.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Human-MoE", None))
        self.pushButton_load_parsing.setText(QCoreApplication.translate("Form", u"Load Parsing", None))
        self.pushButton_load_pose.setText(QCoreApplication.translate("Form", u"Load Pose", None))
        self.pushButton_save_output.setText(QCoreApplication.translate("Form", u"Save Output", None))
        self.pushButton_clear.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.pushButton_save_parsing.setText(QCoreApplication.translate("Form", u"Save Parsing", None))
        self.pushButton_generate.setText(QCoreApplication.translate("Form", u"Generate", None))
        self.label_text_discription.setText(QCoreApplication.translate("Form", u"Text Discription", None))
        self.pushButton_top.setText(QCoreApplication.translate("Form", u"Top", None))
        self.pushButton_skin.setText(QCoreApplication.translate("Form", u"Skin", None))
        self.pushButton_outer.setText(QCoreApplication.translate("Form", u"Outer", None))
        self.pushButton_face.setText(QCoreApplication.translate("Form", u"Face", None))
        self.pushButton_skirt.setText(QCoreApplication.translate("Form", u"Skirt", None))
        self.pushButton_hair.setText(QCoreApplication.translate("Form", u"Hair", None))
        self.pushButton_dress.setText(QCoreApplication.translate("Form", u"Dress", None))
        self.pushButton_headwear.setText(QCoreApplication.translate("Form", u"Headwear", None))
        self.pushButton_pants.setText(QCoreApplication.translate("Form", u"Pants", None))
        self.pushButton_eyeglass.setText(QCoreApplication.translate("Form", u"Eyeglass", None))
        self.pushButton_rompers.setText(QCoreApplication.translate("Form", u"Rompers", None))
        self.pushButton_footwear.setText(QCoreApplication.translate("Form", u"Footwear", None))
        self.pushButton_leggings.setText(QCoreApplication.translate("Form", u"Leggings", None))
        self.pushButton_ring.setText(QCoreApplication.translate("Form", u"Ring", None))
        self.pushButton_belt.setText(QCoreApplication.translate("Form", u"Belt", None))
        self.pushButton_neckwear.setText(QCoreApplication.translate("Form", u"Neckwear", None))
        self.pushButton_wristwear.setText(QCoreApplication.translate("Form", u"Wristwear", None))
        self.pushButton_socks.setText(QCoreApplication.translate("Form", u"Socks", None))
        self.pushButton_tie.setText(QCoreApplication.translate("Form", u"Tie", None))
        self.pushButton_necklace.setText(QCoreApplication.translate("Form", u"Necklace", None))
        self.pushButton_earrings.setText(QCoreApplication.translate("Form", u"Earrings", None))
        self.pushButton_bag.setText(QCoreApplication.translate("Form", u"Bag", None))
        self.pushButton_gloves.setText(QCoreApplication.translate("Form", u"Gloves", None))
        self.pushButton_background.setText(QCoreApplication.translate("Form", u"Background", None))
        self.label.setText("")
    # retranslateUi

